name: Release
permissions:
<<<<<<< HEAD
  contents: write
=======
  contents: write  # Required to create tags [1][4]
  
>>>>>>> b640cd1 (trying to resolve codeQL)
on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Auto-tag
        uses: anthrNick/github-tag-action@v1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
